envFromSecret: grafana-secret
persistence:
  type: pvc
  enabled: true
  existingClaim: grafana-v2
grafana.ini:
  server:
    domain: metrics.longhorn.io
    root_url: https://metrics.longhorn.io
  auth.github:
    enabled: true
    allow_sign_up: true
    scopes: "user:email,read:org"
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
    team_ids: "${LONGHRN_GITHUB_ORG_TEAMS_IDS}"
    allowed_organizations: "longhorn"
    client_id: "${GRAFANA_GITHUB_OAUTH_ID}"
    client_secret: "${GRAFANA_GITHUB_OAUTH_SECRET}"
  auth.anonymous:
    enabled: true
    org_name: "longhorn-public"
    org_role: "Viewer"
ingress:
  enabled: true
  apiVersion: "networking.k8s.io/v1beta1"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/secure-backends: "true"
  hosts:
    - metrics.longhorn.io
  path: /
  tls:
    - secretName: metrics.longhorn.io
      hosts:
        - metrics.longhorn.io
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
                - amd64